### ISSUE TITLE
Package new jujubigdata version

### ISSUE THREAD

**Issue by merlijn-sebrechts** [juju-solutions/jujubigdata#13]
My changes to the Kafka Charm rely on [this commit](https://github.com/juju-solutions/jujubigdata/commit/34369283223218311a857447885a47251e7e8da1#diff-c3cdfd6d76ee42c669d705fbe0c06088). Is it possible to package a new jujubigdata version so I can push my patches upstream?

**Comment by andrewdmcleod** [comment]
Hi Merlijn,

Sure thing - we'll be reviewing the commit this afternoon EU time and may
be able to release it shortly after.

Thanks,
Andrew McLeod

On Tue, Nov 3, 2015 at 10:27 AM, Merlijn Sebrechts <notifications@github.com

**Comment by merlijn-sebrechts** [comment]
Thanks!

2015-11-03 11:46 GMT+01:00 andrewdmcleod notifications@github.com:

**Comment by kwmonroe** [comment]
Hey Merlijn,

jujubigdata v4.5.0 was just released, and includes your update to utils.run_as():

https://pypi.python.org/pypi/jujubigdata/4.5.0

All charms referencing '''pypi: jujubigdata>=4.0.0,<5.0.0''' in resources.yaml will pick up this version on deployment -- this includes all currently promulgated apache-hadoop charms, as well as those in ~bigdata-dev.  Please let us know if you see any issues using this updated library.

Thanks for the PR!

**Comment by galgalesh** [comment]
Hi


The apache-flume-kafka Charm has the following resource:
http://mirrors.gigenet.com/apache/zookeeper/stable/zookeeper-3.4.6.tar.gz

Sadly, this link returns 404 since recently. Is it possible to mirror this
in the amazon s3 bucket? Meanwhile, is there another mirror I can use to
make this installation work?



Kind regards
Merlijn

**Comment by galgalesh** [comment]
Hi all



We wanted do deploy Apache Hadoop Spark today for a demo, however the
Hadoop-plugin Charm seems to be broken.


Error:

unit-plugin-0[6794]: 2016-02-23 07:34:04 INFO
unit.plugin/0.config-changed logger.go:40 Traceback (most recent call
last):

unit-plugin-0[6794]: 2016-02-23 07:34:04 INFO
unit.plugin/0.config-changed logger.go:40   File
"/var/lib/juju/agents/unit-plugin-0/charm/hooks/config-changed", line
14, in <module>

unit-plugin-0[6794]: 2016-02-23 07:34:04 INFO
unit.plugin/0.config-changed logger.go:40     import common

unit-plugin-0[6794]: 2016-02-23 07:34:04 INFO
unit.plugin/0.config-changed logger.go:40   File
"/var/lib/juju/agents/unit-plugin-0/charm/hooks/common.py", line 21,
in <module>

unit-plugin-0[6794]: 2016-02-23 07:34:04 INFO
unit.plugin/0.config-changed logger.go:40     from charmhelpers.core
import charmframework

unit-plugin-0[6794]: 2016-02-23 07:34:04 INFO
unit.plugin/0.config-changed logger.go:40 ImportError: cannot import
name charmframework


Our bundle:

machines:

  '0':

    constraints: 'arch=amd64'

    series: trusty

  '1':

    constraints: 'arch=amd64'

    series: trusty

services:

  compute-slave:

    charm: cs:trusty/apache-hadoop-compute-slave-8

    num_units: 3

    annotations:

      gui-x: "300"

      gui-y: "200"

    to: lxc:1

  hdfs-master:

    charm: cs:trusty/apache-hadoop-hdfs-master-8

    num_units: 1

    annotations:

      gui-x: "600"

      gui-y: "350"

    to: lxc:0

  yarn-master:

    charm: cs:trusty/apache-hadoop-yarn-master-6

    num_units: 1

    annotations:

      gui-x: "600"

      gui-y: "100"

    to: lxc:0

  plugin:

    charm: cs:trusty/apache-hadoop-plugin-7

    annotations:

      gui-x: "900"

      gui-y: "200"

  spark:

    charm: cs:trusty/apache-spark-3

    num_units: 1

    annotations:

      gui-x: "1200"

      gui-y: "200"

    to: lxc:0

  juju-gui:

    charm: cs:trusty/juju-gui

    to: lxc:0

series: trusty

relations:

  - [yarn-master, hdfs-master]

  - [compute-slave, yarn-master]

  - [compute-slave, hdfs-master]

  - [plugin, yarn-master]

  - [plugin, hdfs-master]

  - [spark, plugin]



I suspect this has something to do with the patched version of charmhelpers
that is supposed to ship with the bigdata Charms?




Kind regards
Merlijn Sebrechts

**Comment by andrewdmcleod** [comment]
Hi Merlijn,

There are more recent versions of both the plugin and the spark charm in
the store, are you able to try those?

cs:trusty/apache-hadoop-plugin-10
cs:trusty/apache-spark-6

Andrew

On Tue, Feb 23, 2016 at 9:10 AM, Merlijn Sebrechts <notifications@github.com

**Comment by merlijn-sebrechts** [comment]
Wow, how did this end up here? I thought I was mailing the jujubigdata list. I'll try a newer version.
