### ISSUE TITLE
host.adduser doesn't support group keyword argument

### ISSUE THREAD

**Issue by merlijn-sebrechts** [juju-solutions/jujubigdata#21]
In DistConfig, addusers function in [utils.py](https://github.com/juju-solutions/jujubigdata/blob/master/jujubigdata/utils.py):

```
        for username, details in self.users.items():
        primary_group = None
        groups = details.get('groups', [])
        if groups:
            primary_group = groups[0]
        host.adduser(username, group=primary_group)
        for group in groups:
            host.add_user_to_group(username, group)
```

`host.adduser` doesn't support `group` keyword argument. It seems most of the bigdata Charms use a patched charmhelpers library to circumvent this. The patched charmhelpers causes all kinds of problems when porting Charms to the reactive framework + jujubigdata layer. Is it possible to either merge the adduser patch into charmhelpers or put the patched version in this library?

Thanks!

**Comment by merlijn-sebrechts** [comment]
Pull request https://github.com/juju-solutions/jujubigdata/pull/19 would solve this problem, although I'm not sure how Hadoop permissions will react to the user's primary group not being `hadoop` anymore. Will all users in hadoop group still be able to read files from other users in this group?

**Comment by johnsca** [comment]
I'm leaning more and more toward porting the `host.adduser` change from our branch to upstream charmhelpers.

**Comment by johnsca** [comment]
https://code.launchpad.net/~johnsca/charm-helpers/adduser-group/+merge/278649

**Comment by kwmonroe** [comment]
cosed with #24
